config/routes.rb
Rails.application.routes.draw do

  resources :concerts do
    resources :comments
  end
  get '/' => "concerts#home"

  get '/home' => "concerts#home"
  get '/upcoming' => "concerts#upcoming"
  get '/getcomments/:id' => 'comments#send_comments'
  post '/addcomments/:id' => 'comments#add_comments'

  get '/songsearch' => 'songsearch#main'
  get '/sign_up' => "users#new"
  post '/users' => "users#create"
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  delete '/logout' => "sessions#destroy"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :concert
end

app/models/concert.rb
class Concert < ActiveRecord::Base
	
	has_many :comments
	validates 	:artist, presence: true
	validates	:date, presence: true
	validates	:venue, presence: true
	validates	:city, presence: true
	validates	:ticket_price,  presence: true, numericality: true
	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :password, presence: true
  	validates :username, presence: true
  	validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   helper_method :current_user

  def current_user
  	if @current_user.nil?
  		@current_user = User.find_by(id: session[:user_id])
  	end
  	@current_user
  end  

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		concert = Concert.find(params[:concert_id])
		comment = concert.comments.new(comment_params)
		if comment.save
			flash[:notice] = "Success!"
		end
			redirect_to concert_path(params[:concert_id])

	end
	def send_comments

		artist = Concert.find(params[:id].chars.first)

		artist.comments.order(created_at: :ASC)
		
		render(:json => artist.comments)
	end

	def add_comments
		p params
		concert = Concert.find(params[:concert_id].chars.first)

		comment = concert.comments.new(:title => params[:title],:description => params[:description] )
		p concert
		p comment
		if comment.save 
			puts " SAVED"
		end
		render nothing: true
		
	end

	private
	def comment_params
		return params.require(:comment).permit(:title, :description)
	end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

	def show
		@comment = Comment.new
		@concert = Concert.find(params[:id])
		artists =  RSpotify::Artist.search(@concert.artist)
		@artist = artists[0]
		
		render 'show'
	end

	def upcoming
		@concerts_today = Concert.where(:date => Date.today)
		@concerts_upcoming = Concert.where('date >= ?', DateTime.now)
		.order("extract(day from date) ASC")
		
			render 'upcoming'
	end

	def new
		@concert = Concert.new
		render 'new'
	end

	def index
		@concerts = Concert.all
		render 'index'
	end

	def create
		
		@concert = Concert.new(concert_params)

		if @concert.save 
			flash[:notice] = "Added new concert!"
			redirect_to action: 'index', controller: 'concerts'
		else 
			flash[:alert] = "Creation Failed."
			render 'new'
		end
	end

	def home
		@concerts_today = Concert.where(:date => Date.today)
		@concerts_month = Concert.where('extract(month from date) = ?', Time.now.month).where('extract(year from date) = ?', Time.now.year).order("extract(day from date) ASC")
			render 'home'
	end
	

	def update

	end

	private
	def concert_params
		return params.require(:concert).permit(:venue, :description, :date, :ticket_price, :city, :artist)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
		def new

		render 'new'

	end

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id

			redirect_to '/'
		else
			redirect_to '/login'

		end
		
	end

	def destroy
			session.clear
			redirect_to '/'

	end
end

app/controllers/songsearch_controller.rb
class SongsearchController < ApplicationController
	def main
		render('main')
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  # renders the signup form
  def new
  end



  # receives form and creates a user from that data
  def create
    user = User.new(user_params)
    if user.save
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end   

  private

  def user_params
     params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def pretty_date(date)
		return date.strftime("%B %-d, %Y")
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songsearch_helper.rb
module SongsearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/concerts/home.html.erb
<div class="col-lg-3">
	<div class="panel panel-default">
			<div class="panel-heading">
					<h2 class="panel-title text-center" >Concerts this month</h2>
			</div>
			<div class="panel-body">

				<ul>

					<% @concerts_month.each do |concert| %>
						<li>
							<a href="<%= concert_path(concert.id)%>" style = "font-size: 20px"><%= concert.artist %></a>  <p><%= pretty_date(concert.date) %></p>
						</li>


					<%end%>
				</ul>
			</div>
	</div>
			
</div>
	<div class="col-lg-8">
					
			<div class="panel panel-default">

			<div class="panel-heading">
			<h1 class="panel-title text-center" >Concerts today</h1>
			</div>
			<div class="panel-body">
			<div class="container-fluid">
			<ul>
				<% @concerts_today.each do |concert| %>
				<div class="col-xs-6">
					<a href="<%= concert_path(concert.id)%>"> <h3><%= concert.artist %></a>  <small><%= concert.city %></small></h3></a>
				</div>
				<%end%>	
			</ul>
			
			</div>
			</div>
			


	</div>
</div>
<div class="col-lg-1">
			
</div>

app/views/concerts/index.html.erb
<div class="col-lg-3">	
</div>
		<div class="col-lg-6">
				
			<div class="panel panel-default">
				<div class="panel-heading">
				<h1 class="panel-title text-center" >All Concerts</h1>
				</div>
	
					<div "panel-body">
						<div class="container-fluid">
							<ul>
								<% @concerts.each do |concert| %>
								<li> 
									<div class="col-xs-6">
									<a href="<%= concert_path(concert.id)%>"> <h3><%= concert.artist %></a>  <small><%= concert.city %></small></h3>
									</div>	
								</li>
								<% end %>
							</ul>
							
						</div>
					</div>
					
					</div>
				</div>
		<div class="col-lg-3">
			
		</div>
				

app/views/concerts/new.html.erb
<div class="col-lg-3">
</div>
	<div class="col-lg-6">

		<div class="panel panel-default panel_white">
				<div class="panel-heading">
						<h2 class="panel-title text-center" >New Concert</h2>
				</div>
				<div class="panel-body">
				<div class="container-fluid">

					<%= form_for(@concert) do |f| %>

					<div class="input-group">
						<%= f.label :city, class: "form-label" %>
						<%= f.text_field :city, class: "form-control"%>
					</div>

					<div class="input-group">
						<%= f.label :artist, class: "form-label" %>
						<%= f.text_field :artist, class: "form-control" %>
					</div>
					
					<div class="input-group">
						<%= f.label :date, class: "form-label" %>
						<%= f.date_field :date, class: "form-control" %>
					</div>

					<div class="input-group">
						<%= f.label :venue, class: "form-label" %>
						<%= f.text_field :venue, class: "form-control" %>
					</div>
					
					<div class="input-group">
						<%= f.label :description, class: "form-label" %>
						<%= f.text_field :description, class: "form-control" %>
					</div>
					
					<div class="input-group">
						<%= f.label :Ticket_price, class: "form-label" %>
						<%= f.number_field :ticket_price, class: "form-control" %>
					</div>
					
						 <div class="checkbox">
						    <label>
						      <input type="checkbox"> All info is correct?
						    </label>
						  </div>
						<button class="btn btn-default" type="submit">Submit</button>
					<% end %>

				
				</div>
				</div>
				


		</div>
	</div>
<div class="col-lg-3">
			
</div>
	

app/views/concerts/show.html.erb
<div class="col-lg-1">

</div>
	<div class="col-lg-7">
					
			<div class="panel panel-default">

			<div class="panel-body" style="padding: 0px;">
<div class="container-fluid">
			<h1 class="jumbotron" style="padding: 5px"> <%= @concert.artist %> <br><small><%= "At " + @concert.venue%></small></h1>

				
				<div class="col-xs-6">
					<img class= "img-rounded" src="<%=@artist.images[0]['url']%>" width = "200px">						
						<iframe src="<%= @artist.top_tracks(:US)[0].preview_url%>" width="200" height="70" frameborder="0" allowtransparency="true"></iframe>	
						<br>
						<button class = "btn btn-primary albumsLink" id = "<%= @artist.id %>">View Albums</button>	
										
				</div>

						<div class="col-xs-6">
							<p> <%= @concert.artist + " At " + @concert.venue + " ticket price is: $" + @concert.ticket_price.to_s%> </p>
							<p> <%= "Concert will be held on " + pretty_date(@concert.date) + " in beautiful " + @concert.city %></p>
						<p><strong>Genres:</strong></p> 
								<ul id='genreList'>
								<% @artist.genres.each do |genre| %> 
								
								<li>
									<p><small><%= genre.upcase %></small></p>
								</li>
								
								<%end%>
								</ul>
								<br>
		<% if current_user.present? %>

			<div class="panel panel-default panel_white_trans" style="padding: 10px;">	

				<div class="panel-heading panel_trans text-center">

					<h1 class="panel-title"><button class="btn btn-primary" id="commentHeading">Add Comment</button></h1>
					
				</div>	
				
				<div class="panel-body commentForm">
					<script>
						$('.commentForm').toggle()
					</script>
					
					<%= form_for([@concert, @comment]) do |f| %>

					<div class="input-group">
						<%= f.label :title, class: "form-label" %>
						<%= f.text_field :title, class: "form-control titleInput"%>
					</div>
					<div class="input-group">
						<%= f.label :description, class: "form-label " %>
						<%= f.text_field :description, class: "form-control descriptionInput"%>
					</div>
					<%end%>

					
					
					<button class="btn btn-primary" style="margin-top: 15px" type="submitComments">Submit</button>

					<script>
					
						$('button[type="submitComments"]').on('click', postComments);

						function postComments() {
							console.log('<%= @concert.id %>')
							var jsonpack = {
									concert_id: "<%= @concert.id %>",
									title: $('.titleInput').val(),
									description: $('.descriptionInput').val(),
									authenticity_token: window._token
								}
								console.log(jsonpack)
							$.post('/addcomments/'+'<%= @artist.id %>', jsonpack)
							$('.titleInput').prop('value', '');
							$('.descriptionInput').prop('value', '');
							$('.commentForm').slideToggle();
							$('#genreList').slideToggle();
						}

					</script>
					
				</div>
				
			</div>
			<% end %>
						</div>


		</div>
	</div>
</div>
</div>

<div class="col-lg-4">
	<div class="container-fluid">
	
			<div class="panel panel-default" style="padding: 10px;">
						
				<div class="panel-heading text-center">
					<h1 class="panel-title ">Comments</h1>
				</div>	

				
			
			</div>
		<div class="commentScroll">
			<div class="comments">
			<script>

				function getComments() {
					var url = '/getcomments/' + "<%= @concert.id %>"
					console.log(url)

					$.get(url, handleComments)
				}
				var data_array = []
				function handleComments(data) {
					$('.comments').empty();
					data.sort(function(a,b){return b.id-a.id})
					data.forEach(function(comment){
						var line1 = "<div class='panel panel-default' style='padding: 10px;'>"
						var line2 = "<div class='panel-heading'>"
						var line3 = "<h4>" + comment.title + "</h4>"
						var line4 = "<h4><small>" + comment.description + "</small></h4>"
						var line5 = "</div>"
						var line6 = "</div>"
						$('.comments').append( line1 + line2 + line3 + line4 + line5 + line6);


					});

				};
				setInterval(function(){getComments()}, 1000);
				getComments();
			</script>
			</div>
		</div>

			

			

	</div>		
</div>


<div class="modal fade scroll" id="albumModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Albums</h4>
      </div>
      <div class="modal-body">
      	<div class="container-fluid">
        <ul id='album_results' style="padding-left:0;">
        </ul>
        </div>
      </div>
          </div>
  </div>
</div>
<div class="modal fade" id="tracksModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Tracks</h4>
      </div>
      <div class="modal-body">
      	<div class="container-fluid">
      	<div class="col-s-6">
        <ul id='tracks_results' style="padding-left:0;">

        </ul>
        </div>

        </div>
      </div>
          </div>
  </div>
</div>

<script>
$('.albumsLink').on('click', function(event){
	event.preventDefault;
	
		console.log(event.target.id);
		var searchTerm = event.target.id
		var  url = "https://api.spotify.com/v1/artists/"+ searchTerm +"/albums" 
		console.log (url)
		var request = $.get(url, handleAlbums)
	});

function handleAlbums(data) {
	console.log(data)
	$('#album_results').empty()
	var previousName = ""
	data.items.forEach(function(album,index) {
		if (previousName != album.name){

			$('#album_results').append('<li>'+
				"<button style='margin-top:5px;margin-bottom:5px;' class = 'btn btn-default' type='album' id = '"+ album.id + "'>" +'<span style = "font-size:22px; line-height:2;">'+
				 album.name + '</span>'+ 
				  " <img class = 'img-thumbnail pull-right' src='" + album.images[0].url +"' width=11%>" +"</button>"+'</li>')
		}
	 previousName = album.name
	});

	$('button[type="album"]').on('click', function(event){		
		console.log(event.target.id);
		var searchTerm = event.target.id
		var  url = "https://api.spotify.com/v1/albums/"+ searchTerm +"/tracks" 
		console.log (url)
		var request = $.get(url, handleTracks)
	});

	$('#albumModal').modal('toggle')

};

function handleTracks(data) {
	console.log(data)
	$('#albumModal').modal('toggle')

	$('#tracks_results').empty()
	var previousName = ""

	data.items.forEach(function(track) {
		$('#tracks_results').append('<li>' + "<button  type='track' id= '"+track.preview_url+"' class='btn btn-default'>"+ track.name +"</button>" +'</li>');

		
	});
	$('button[type="track"]').on('click', function(event) {
		console.log('clicked')
		$('iframe').prop('src', event.target.id)
	})
	$('#tracksModal').modal('toggle')
};


$('button[id="commentHeading"]').on('click', function(){ 
						event.preventDefault; 
						console.log('something');
						$('#genreList').slideToggle();
						$('.commentForm').slideToggle();
					});
</script>

app/views/concerts/upcoming.html.erb
<div class="col-lg-3">
	<div class="panel panel-default">
			<div class="panel-heading">
					<h2 class="panel-title text-center" >Concerts Today</h2>
			</div>
			<div class="panel-body">

				<ul>

					<% @concerts_today.each do |concert| %>
						<li>
							<a href="<%= concert_path(concert.id)%>" style = "font-size: 20px"><%= concert.artist %></a>  <p><%= pretty_date(concert.date) %></p>
						</li>


					<%end%>
				</ul>
			</div>
	</div>
			
</div>
	<div class="col-lg-8">
					
			<div class="panel panel-default">

			<div class="panel-heading">
			<h1 class="panel-title text-center" >Concerts Upcoming</h1>
			</div>
			<div class="panel-body">
			<div class="container-fluid">
			<ul>
				<% @concerts_upcoming.each do |concert| %>
				<div class="col-xs-6">
					<a href="<%= concert_path(concert.id)%>"> <h3><%= concert.artist %></a>  <small><%= concert.city %></small></h3></a>
				</div>
				<%end%>	
			</ul>
			
			</div>
			</div>
			


	</div>
</div>
<div class="col-lg-1">
			
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConcertSite</title>
  
  <%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<%= render './partials/header' %>
<div class="container-fluid" style="background-color: transparent;">

  

						<%= yield %>

			
</div>

<%= render './partials/footer'%>
</body>
</html>

app/views/partials/_footer.html.erb
<nav class="navbar navbar-inverse navbar-fixed-bottom" >
  <div class="container-fluid" >
     <div class="navbar-header">
		<h5 style="color: white; line-height: 2.3;">Copyright Kaysser Kayyali @Ironhack <%= Time.now.year %></h5>
    
    </div>
    
    	<ul class="nav navbar-nav pull-right">
	  		<% if current_user.present? %>		
		        <li><a href="<%= new_concert_path %>">Add new Concert</a></li>
		    <% end%>

	   	</ul>
  </div>
</nav>

app/views/partials/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= home_path %>">Kaysser's Music Network</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav pull-right">
      <% if current_user.present? %>    
            
            <li><%=link_to "Logout", '/logout', :method => :delete %></li>  
        <% else %>
          <li> <%=link_to "Login", '/login'%></li>  
          <li> <%=link_to "Sign Up", '/sign_up'%></li>  
        <% end%>
      </ul>
      <div class="nav navbar-brand pull-right">
  <% if current_user.present? %>
  Signed in as 
      <%= current_user.username %>
    <% end %>
    

    </div>
      <ul class="nav navbar-nav pull-left">
        <li><a href="<%= home_path %>">Home</a></li>
        <li><a href="<%=upcoming_path%>">Upcoming Concerts</a></li>
        <li><a href="<%= concerts_path %>">All concerts</a></li>
        <li><a href="<%= songsearch_path %>">Song Search</a></li>
      </ul>
    
      
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_reactshow.html.erb
<script>

<div style="height:300px; width: 300px; margin-left: 100px;">
<%= render './partials/reactshow' :locals => {:greeting => 'Hello world', :x => 36}%>
</div>

</script>




<%= react_component ('Main', searchResult: <%= search %>) %>

app/views/songsearch/main.html.erb
<div class="col-lg-1">

</div>
	<div class="col-lg-7">
					
		<div class="panel panel-default">

			<div class="panel-body" style="padding: 0px;">
				<div class="container-fluid">
					<h1 class="jumbotron" style="border-radius:20px; padding: 20px">Search Track<br><small>Previews</small></h1>
					
						<div class="col-md-6">
							
								<div class="input-group  has-validation">
									<input class="form-control has-success" name = "search">
									<span class="input-group-btn">
									<button type="submit" class="btn btn-default" onClick="onSearchSubmit()" >Search</button>
									</span>
								</div>

						</div>
						<div class="col-md-6">
							<div class="widget">
								<div class="cover">
								<img src="https://i.scdn.co/image/04da6dfc1f5f45fdeba938a0cc71cf372524fd43" class="js-player-image">
								</div>
								<div class="heading">
								<!-- Try adding/removing these classes: -->
								<!-- disabled -->
								<!-- playing -->
								<div class="btn-play" onclick="onPlayButtonClick()"></div>

								<div class="metadata">
								  <p class="title">Hunger of The Pine</p>
								  <a class="over-hover"href="#" onclick="$('#artistModal').modal()"><p class="author">alt-J</p></a>

								  <div class="seekbar">
								    <progress value="0" max="30"></progress>
								  </div>
								</div>
								</div>
								

								<audio src="https://p.scdn.co/mp3-preview/8e9c5ffdc38e91659bfe8b6bd44650dfc25a3d31" class="js-player" ontimeupdate='updateTrackTime()'></audio>
							</div>
							
						
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-4">
		
	</div>

	<div class="modal fade" id="artistModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="artistModalLabel">Please search for a new artist</h4>
	      </div>
	      <div class="modal-body">
			<div class="container-fluid">
				<div class="col-xs-6">
					<img id='image' src='' width="250px">
				</div>
				<div class="col-xs-6">
					<div class="container-fluid">
						<div class="row" id="genre">	
						</div>
						<div class="row">
							<h5>Followers on Spotify:</h5>
							<span id="followers">Search First</span>
						</div>
						<div class="row">
							<h5>Popularity:</h5>
							<span id="pop">Search First</span>
						</div>	
					</div>
				</div>
			</div>
			

	        	<!-- 
				 
				$('#pop').val(artist.popularity); 
				
 -->
	      </div>
	    
	    </div>
	  </div>
	</div>

app/views/users/new.html.erb
<div class="form col-lg-3 white-text">
<h1 class="jumbotron black-text" style="border-radius:20px;">Sign up!</h1>
<%= form_for :user, url: '/users' do |f| %>
	<div class = "form-group has-validation">	
  Name <%= f.text_field :username, class: "form-control white-text" %>
  </div>
	<div class = "form-group has-validation">  
  Email <%= f.text_field :email, class: "form-control white-text" %>
  </div>
	<div class = "form-group has-validation">
  Password  <%= f.password_field :password, class: "form-control white-text" %>
  </div>
	<div class = "form-group has-validation">
  Confirmation 
  <%= f.password_field :password_confirmation, class: "form-control white-text " %>
  </div>
  <%= f.submit "Submit", class: 'btn btn-primary' %>

<% end %>
</div>